name: Changelog check

on:
  pull_request:
    branches: master

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: bash .github/scripts/changelog/checker.sh
